### ISSUE TITLE
organisms/HeaderUnLoggedIn.vue

### ISSUE THREAD

**Issue by Kunado** [enpitut2018/task_driver_frontend#13]
# コンポーネント定義
| 名前 | 説明 |
| :--- | :--- |
| `HeaderUnloggedIn.vue` | 未ログイン時用ヘッダー |

# 子コンポーネント

# 備考

**Comment by lmn8cs** [comment]
・右上に「ログイン」「ユーザ登録」をbuttonReflect使って作る
・左上にFolivora

**Comment by lmn8cs** [comment]
ヘッダー専用のボタンをmixin.scssでつくる
