### ISSUE TITLE
pages/signUp.vue

### ISSUE THREAD

**Issue by Kunado** [enpitut2018/task_driver_frontend#15]
# ページ定義
| 名前 | テンプレート | 説明 |
| :--- | :--- | :--- |
| `signUp.vue` | `unauthenticated` | ユーザー登録用ページ |

# 子コンポーネント

# 備考
* `{"user": {"username": "", "password": "", "password_confirmation": "", "email": ""}}`をaxiosを使って`/v1/sign_up`にPOST

**Comment by itumizu** [comment]
実装済みです
