### ISSUE TITLE
pages/resetPassword.vue

### ISSUE THREAD

**Issue by Kunado** [enpitut2018/task_driver_frontend#46]
# ページ定義
| 名前 | テンプレート | 説明 |
| :--- | :--- | :--- |
| `resetPassword.vue` | `unauthenticated.vue` | パスワードリセット用のページ |

# 備考
* 参考になりそう(未読): [Use password reset mechanisms with JSON-only communication · Issue #2405 · plataformatec/devise](https://github.com/plataformatec/devise/issues/2405)
* `<NUXT_URL>/resetPassword?token=XXXXXXX` みたいなリンクを生成してメールに入れて送るみたいな実装になるのか？ `resetPassword` 側でtokenを新規パスワードと一緒にrailsに投げる

**Comment by itumizu** [comment]
すでに実装済みです
